remove ; from endilnes

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -75,119 +75,119 @@ x-airflow-common:
   # user: "${AIRFLOW_UID:-50000}:0"
 
 services:
-  airflow-webserver:
-    <<: *airflow-common
-    command: webserver
-    ports:
-      - "8080:8080"
-    healthcheck:
-      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 30s
-    restart: always
-    depends_on:
-      airflow-init:
-        condition: service_completed_successfully
-
-  airflow-scheduler:
-    <<: *airflow-common
-    command: scheduler
-    healthcheck:
-      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 30s
-    restart: always
-    depends_on:
-      airflow-init:
-        condition: service_completed_successfully
-
-  airflow-init:
-    <<: *airflow-common
-    entrypoint: /bin/bash
-    # yamllint disable rule:line-length
-    command:
-      - -c
-      - |
-        if [[ -z "${AIRFLOW_UID}" ]]; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
-          echo "If you are on Linux, you SHOULD follow the instructions below to set "
-          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
-          echo "For other operating systems you can get rid of the warning with manually created .env file:"
-          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
-          echo
-        fi
-        one_meg=1048576
-        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
-        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
-        disk_available=$$(df / | tail -1 | awk '{print $$4}')
-        warning_resources="false"
-        if (( mem_available < 4000 )) ; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
-          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
-          echo
-          warning_resources="true"
-        fi
-        if (( cpus_available < 2 )); then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
-          echo "At least 2 CPUs recommended. You have $${cpus_available}"
-          echo
-          warning_resources="true"
-        fi
-        if (( disk_available < one_meg * 10 )); then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
-          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
-          echo
-          warning_resources="true"
-        fi
-        if [[ $${warning_resources} == "true" ]]; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
-          echo "Please follow the instructions to increase amount of resources available:"
-          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
-          echo
-        fi
-
-        mkdir -p /opt/airflow/{logs,dags,plugins,db,data}
-        
-        chown -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,db,data}
-        exec /entrypoint airflow version && airflow config get-value database sql_alchemy_conn
-    # yamllint enable rule:line-length
-    environment:
-      <<: *airflow-common-env
-      _AIRFLOW_DB_MIGRATE: 'true'
-      _AIRFLOW_WWW_USER_CREATE: 'true'
-      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
-      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
-      _PIP_ADDITIONAL_REQUIREMENTS: ''
-    user: "0:0"
-    volumes:
-      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
-      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
-      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
-      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
-      - ${AIRFLOW_PROJ_DIR:-.}/db:/opt/airflow/db
-      - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
-
-  airflow-cli:
-    <<: *airflow-common
-    profiles:
-      - debug
-    environment:
-      <<: *airflow-common-env
-      CONNECTION_CHECK_MAX_COUNT: "0"
-    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
-    command:
-      - bash
-      - -c
-      - airflow
+#  airflow-webserver:
+#    <<: *airflow-common
+#    command: webserver
+#    ports:
+#      - "8080:8080"
+#    healthcheck:
+#      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+#      interval: 30s
+#      timeout: 10s
+#      retries: 5
+#      start_period: 30s
+#    restart: always
+#    depends_on:
+#      airflow-init:
+#        condition: service_completed_successfully
+#
+#  airflow-scheduler:
+#    <<: *airflow-common
+#    command: scheduler
+#    healthcheck:
+#      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
+#      interval: 30s
+#      timeout: 10s
+#      retries: 5
+#      start_period: 30s
+#    restart: always
+#    depends_on:
+#      airflow-init:
+#        condition: service_completed_successfully
+#
+#  airflow-init:
+#    <<: *airflow-common
+#    entrypoint: /bin/bash
+#    # yamllint disable rule:line-length
+#    command:
+#      - -c
+#      - |
+#        if [[ -z "${AIRFLOW_UID}" ]]; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+#          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+#          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+#          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+#          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+#          echo
+#        fi
+#        one_meg=1048576
+#        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+#        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+#        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+#        warning_resources="false"
+#        if (( mem_available < 4000 )) ; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+#          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if (( cpus_available < 2 )); then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+#          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if (( disk_available < one_meg * 10 )); then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+#          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if [[ $${warning_resources} == "true" ]]; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+#          echo "Please follow the instructions to increase amount of resources available:"
+#          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+#          echo
+#        fi
+#
+#        mkdir -p /opt/airflow/{logs,dags,plugins,db,data}
+#
+#        chown -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,db,data}
+#        exec /entrypoint airflow version && airflow config get-value database sql_alchemy_conn
+#    # yamllint enable rule:line-length
+#    environment:
+#      <<: *airflow-common-env
+#      _AIRFLOW_DB_MIGRATE: 'true'
+#      _AIRFLOW_WWW_USER_CREATE: 'true'
+#      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+#      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+#      _PIP_ADDITIONAL_REQUIREMENTS: ''
+#    user: "0:0"
+#    volumes:
+#      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
+#      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
+#      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
+#      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
+#      - ${AIRFLOW_PROJ_DIR:-.}/db:/opt/airflow/db
+#      - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
+#
+#  airflow-cli:
+#    <<: *airflow-common
+#    profiles:
+#      - debug
+#    environment:
+#      <<: *airflow-common-env
+#      CONNECTION_CHECK_MAX_COUNT: "0"
+#    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+#    command:
+#      - bash
+#      - -c
+#      - airflow
 
 # -------------- elastic -------------------
 
@@ -197,18 +197,19 @@ services:
       - certs:/usr/share/elasticsearch/config/certs
     user: "0"
     command: >
-      bash -c '
+      bash -c '''
+        # set -x # uncomment when debugging :)
         if [[ -z ${ELASTIC_PASSWORD} ]]; then
-          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
-          exit 1;
+          echo "Set the ELASTIC_PASSWORD environment variable in the .env file"
+          exit 1
         elif [[ -z ${KIBANA_PASSWORD} ]]; then
-          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
-          exit 1;
-        fi;
+          echo "Set the KIBANA_PASSWORD environment variable in the .env file"
+          exit 1
+        fi
         if [ ! -f config/certs/ca.zip ]; then
-          echo "Creating CA";
-          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
-          unzip config/certs/ca.zip -d config/certs;
+          echo "Creating CA"
+          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip
+          unzip config/certs/ca.zip -d config/certs
         fi;
         if [ ! -f config/certs/certs.zip ]; then
           echo "Creating certs";
@@ -226,26 +227,26 @@ services:
           "      - localhost\n"\
           "    ip:\n"\
           "      - ${ELASTIC_IP}\n"\
-          > config/certs/instances.yml;
-          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
-          unzip config/certs/certs.zip -d config/certs;
+          > config/certs/instances.yml
+          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key
+          unzip config/certs/certs.zip -d config/certs
         fi;
         echo "Setting file permissions"
-        chown -R root:root config/certs;
-        find . -type d -exec chmod 750 \{\} \;;
-        find . -type f -exec chmod 640 \{\} \;;
-        echo "Waiting for Elasticsearch availability";
+        chown -R root:root config/certs
+        find . -type d -exec chmod 750 \{\} \;
+        find . -type f -exec chmod 640 \{\} \;
+        echo "Waiting for Elasticsearch availability"
         until curl -s --cacert config/certs/ca/ca.crt ${ELASTIC_HOST} | grep "missing authentication credentials"; do
           echo "Elasticsearch not available waiting ..."
           sleep 30
         done
-        echo "Setting kibana_system password";
+        echo "Setting kibana_system password"
         until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" "${ELASTIC_HOST}/_security/user/kibana_system/_password" -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep "^{}"; do
-          echo "Couldn't set Kibana password retrying ..."
-          sleep 10;
-        done;
-        echo "All done!";
-      '
+          echo "Could not set Kibana password retrying ..."
+          sleep 10
+        done
+        echo "All done!"
+      '''
     healthcheck:
       test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
       interval: 1s
@@ -337,6 +338,8 @@ services:
 
 volumes:
   certs:
+    driver: local
+  resources:
     driver: local
   esdata01:
     driver: local
